using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace UNote.Editor
{
    ///////////////////////////////////////////////////////
    // Auto generated by PathConstGenerator
    ///////////////////////////////////////////////////////
    [Flags]
    public enum NoteTags
    {
        None = 0,
        All = ~0,
    }
}
