namespace UNote.Editor
{
    ///////////////////////////////////////////////////////
    // Auto generated by NoteTagConstGenerator
    ///////////////////////////////////////////////////////
    [System.Flags]
    public enum NoteTags
    {
        None = 0,
        All = ~0,
        Todo = 1 << 0,
        Bug = 1 << 1,
    }
}
