using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace UNote.Editor
{
    public class NoteTagConstGenerator
    {
        internal static void Generate()
        {
            string filePath = $"{PathUtil.GetRootPath()}/Editor/Scripts/AutoGenerated/NoteTags.cs";

            StringBuilder builder = StringUtil.StringBuilder;
            
            builder.AppendLine("namespace UNote.Editor");
            builder.AppendLine("{");
            builder.AppendLine("    ///////////////////////////////////////////////////////");
            builder.AppendLine("    // Auto generated by NoteTagConstGenerator");
            builder.AppendLine("    ///////////////////////////////////////////////////////");
            builder.AppendLine("    [System.Flags]");
            builder.AppendLine("    public enum NoteTags");
            builder.AppendLine("    {");
            builder.AppendLine("        None = 0,");
            builder.AppendLine("        All = ~0,");

            List<UNoteTagData> tagDataList = UNoteSetting.TagList;
            for (int i = 0; i < tagDataList.Count; ++i)
            {
                builder.AppendLine($"        {tagDataList[i].TagName} = 1 << {i},");
            }
            
            builder.AppendLine("    }");
            builder.AppendLine("}");
            
            File.WriteAllText(filePath, builder.ToString(), Encoding.UTF8);
            AssetDatabase.Refresh();
        }
    }
}
